In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [1]:
import numpy as np
import pandas as pd

In [11]:
data = pd.read_csv('/content/gdrive/MyDrive/Online Sales Data.csv')

df = pd.DataFrame(data)

In [6]:
df.shape

(240, 9)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB

In [8]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [9]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [24]:
# Best-Selling Products - According to Total Revenue

best_selling = (
    df.groupby('Product Name')['Total Revenue']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)
best_selling.head(10)

                        Product Name  Total Revenue
0                Canon EOS R5 Camera        3899.99
1                         LG OLED TV        2599.98
2                MacBook Pro 16-inch        2499.99
3          Apple MacBook Pro 16-inch        2399.00
4                      iPhone 14 Pro        1999.98
5                       Peloton Bike        1895.00
6             HP Spectre x360 Laptop        1599.99
7                         Roomba i7+        1599.98
8              Garmin Forerunner 945        1599.97
9  Samsung Odyssey G9 Gaming Monitor        1499.99

In [32]:
# Best-Selling Products - According to Units Sold

best_selling_units = (
    df.groupby('Product Name')['Units Sold']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)
best_selling_units.head(10)

                              Product Name  Units Sold
0                Hanes ComfortSoft T-Shirt          10
1  The Catcher in the Rye by J.D. Salinger           7
2                         Nike Air Force 1           6
3           Gap Essential Crewneck T-Shirt           6
4                     Yeti Rambler Tumbler           6
5           Spalding NBA Street Basketball           6
6                  Adidas 3-Stripes Shorts           5
7                Calvin Klein Boxer Briefs           5
8               Titleist Pro V1 Golf Balls           5
9            Under Armour HeatGear T-Shirt           5

In [52]:
# Monthy Analysis

df['Date'] = pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month_name()

monthy_sales = (
    df.groupby('Month')['Total Revenue']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)

monthy_sales

      Month  Total Revenue
0   January       14548.32
1     March       12849.24
2     April       12451.69
3  February       10803.37
4       May        8455.49
5      June        7384.55
6    August        7278.11
7      July        6797.08

In [33]:
# Revenue by Category

revenue_byCategory = (
    df.groupby('Product Category')['Total Revenue']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)

revenue_byCategory

  Product Category  Total Revenue
0      Electronics       34982.41
1  Home Appliances       18646.16
2           Sports       14326.52
3         Clothing        8128.93
4  Beauty Products        2621.90
5            Books        1861.93

In [53]:
# Revenue By Region

region_analysis = (
    df.groupby('Region')['Total Revenue']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)

region_analysis

          Region  Total Revenue
0  North America       36844.34
1           Asia       22455.45
2         Europe       21268.06

In [36]:
# Revenue By Payment Method

payment_methodAnalysis = (
    df.groupby('Payment Method')['Total Revenue']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)

payment_methodAnalysis

print("\n")

  Payment Method  Total Revenue
0    Credit Card       51170.86
1         PayPal       21268.06
2     Debit Card        8128.93

In [41]:
# Region & Product Category Analysis

region_product = pd.pivot_table(
    df,
    values = 'Total Revenue',
    index = 'Region',
    columns = 'Product Category',
    aggfunc = 'sum'
)

region_product

Product Category,Beauty Products,Books,Clothing,Electronics,Home Appliances,Sports
Region,,,,,,
Asia,NaN,NaN,8128.93,NaN,NaN,14326.52
Europe,2621.9,NaN,NaN,NaN,18646.16,NaN
North America,NaN,1861.93,NaN,34982.41,NaN,NaN

In [44]:
# Monthly Revenue by Category

monthly_revenue = pd.pivot_table(
    df,
    values = 'Total Revenue',
    index = 'Month',
    columns = 'Product Category',
    aggfunc = 'sum'
)

monthly_revenue

Product Category,Beauty Products,Books,Clothing,Electronics,Home Appliances,Sports
Month,,,,,,
April,201.48,220.85,769.80,6709.91,1989.85,2559.80
August,170.70,192.87,769.91,3066.96,1668.96,1408.71
February,331.98,422.91,1284.81,2899.88,2869.92,2993.87
January,699.95,308.86,1789.84,7999.90,2169.94,1579.83
July,464.00,163.88,1095.48,2006.97,1417.87,1648.88
June,209.49,149.86,579.45,3599.93,1479.89,1365.93
March,417.00,252.83,1009.76,4499.90,5059.91,1609.84
May,127.30,149.87,829.88,4198.96,1989.82,1159.66

In [45]:
# Payment Method, Region wise Analysis

paymentMethod_region = pd.pivot_table(
    df,
    values = 'Total Revenue',
    index = 'Payment Method',
    columns = 'Region',
    aggfunc = 'sum'
)

paymentMethod_region

Region              Asia    Europe  North America
Payment Method
Credit Card     14326.52       NaN       36844.34
Debit Card       8128.93       NaN            NaN
PayPal               NaN  21268.06            NaN

In [51]:
# Units Sold Per Category

units_category = (
    df.groupby('Product Category')['Units Sold']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
)

units_category

  Product Category  Units Sold
0         Clothing         145
1            Books         114
2           Sports          88
3      Electronics          66
4  Home Appliances          59
5  Beauty Products          46

In [49]:
# Purchasing Pattern - Monthly/Category/Units Sold

purchase_monthly = pd.pivot_table(
    df,
    values = 'Units Sold',
    index = 'Product Category',
    columns = 'Month',
    aggfunc = 'sum'
)

purchase_monthly

Month             April  August  February  January  July  June  March  May
Product Category
Beauty Products       6       6         7        5     5     6      6    5
Books                15      13        16       14    12    14     17   13
Clothing             20      12        19       16    18    19     24   17
Electronics           9       7        12       10     6     7     10    5
Home Appliances       7       5         8        6     7     7      9   10
Sports                8       9        15       17     5     8     16   10

In [50]:
# Purchasing Pattern - Category/Units Sold

category_units = (
    df.groupby('Product Category')['Units Sold']
    .sum()
    .reset_index()
)

category_units

  Product Category  Units Sold
0  Beauty Products          46
1            Books         114
2         Clothing         145
3      Electronics          66
4  Home Appliances          59
5           Sports          88